export default [
  {value: '', label: 'Choose'},
  {value: 'backend_developer', label: 'Backend developer'},
  {value: 'business_developer', label: 'Business developer'},
  {value: 'ceo', label: 'CEO'},
  {value: 'cfo', label: 'CFO'},
  {value: 'cmo', label: 'CMO'},
  {value: 'coo', label: 'COO'},
  {value: 'cpo', label: 'CPO'},
  {value: 'cto', label: 'CTO'},
  {value: 'data_scientist', label: 'Data scientist'},
  {value: 'director', label: 'Director'},
  {value: 'frontend_developer', label: 'Frontend developer'},
  {value: 'fullstack_developer', label: 'Fullstack developer'},
  {value: 'head_of_marketing', label: 'Head of marketing'},
  {value: 'head_of_sales', label: 'Head of sales'},
  {value: 'marketing_manager', label: 'Marketing manager'},
  {value: 'marketing_specialist', label: 'Marketing specialist'},
  {value: 'president', label: 'President'},
  {value: 'product_manager', label: 'Product manager'},
  {value: 'product_owner', label: 'Product owner'},
  {value: 'sales_manager', label: 'Sales manager'},
  {value: 'software_engineer', label: 'Software engineer'},
  {value: 'ux_designer', label: 'UX designer'},
  {value: 'vp_of_engineering', label: 'VP of engineering'},
  {value: 'vp_of_growth', label: 'VP of growth'},
  {value: 'vp_of_marketing', label: 'VP of marketing'},
  {value: 'vp_of_operations', label: 'VP of operations'},
  {value: 'vp_of_sales', label: 'VP of sales'},
  {value: 'other', label: 'Other'}
];
